### Local Configuration Variables ###
HS_PATH: /home/ablemann/projects/hs_xdci
HOST_SSL_DIR: /home/ablemann/projects/hs_xdci/hs-certs
HS_DATABASE: pg.development.sql
HS_LOG_FILES: /home/ablemann/projects/hs_xdci/log
HS_SERVICE_UID: 1000
HS_SERVICE_GID: 1000

### Deployment Options ###
USE_NGINX: false
USE_SSL: false
USE_SECURITY: false
USE_HTTP_AUTH: false

### nginx Configuration Variables ###
FQDN_OR_IP: localhost
NGINX_DIR: /home/ablemann/projects/hs_xdci/nginx

### SSL Configuration Variables ###
SSL_CERT_DIR: /home/hydro/hydroshare/nginx/cert-files
SSL_CERT_FILE: hydrodev-vb.example.org.cert
SSL_KEY_FILE: hydrodev-vb.example.org.key

### REQUIRES BLANK LINE AFTER LAST VARIABLE DEFINITION ###
