### docker-compose variables ###
HS_SHARED_VOLUME: /home/hydro/github/hydroshare:/home/docker/hydroshare

### Local Configuration Variables ###
HS_PATH: /home/hydro/github/hydroshare
HOST_SSL_DIR: /home/hydro/hs-certs

### Deployment Options ###
USE_NGINX: true
USE_SSL: true

### nginx Configuration Variables ###
HS_NGINX_DIR: /home/hydro/github/hydroshare/nginx
HS_NGINX_IMG: hs-nginx
HS_NGINX: web-nginx
HS_CNAME: hydroshare_hydroshare_1

### SSL Configuration Variables ###
FQDN_OR_IP: localhost
SSL_CERT_DIR: /home/hydro/github/hydroshare/nginx/cert-files
SSL_CERT_FILE: hydrodev-vb.example.org.cert
SSL_KEY_FILE: hydrodev-vb.example.org.key
